In [55]:
%precision 16
%matplotlib inline
import numpy as np
import scipy as sp
import scipy.linalg as sl

from pprint import pprint

# Creating matrices to compare with the outputs from C++ Jacobi

In [56]:
A = np.array([[10., 2., 3., 5.],
              [1., 14., 6., 2.],
              [-1., 4., 16., -4],
              [5., 4., 3., 11.]])

b = np.array([1., 2., 3., 4.])

# An initial guess at the solution.
x = np.zeros_like(b)
# With no prior knowledge we can't really do anything  
# other than just impose a vector of zeros

# A user-defined iteration tolerance
tol = 1.e-6  

# A user-specified upper limit on number of iterations to stop at
# if we don't hit tolerance
it_max = 1000  

# Store the residuals for later plotting - we don't know how long this needs to
# be as we don't know how many iterations we will conduct, so initialise an 
# empty list which we will append results to in the loop below
residuals = []
# and also change in solution between iterations
delta_x = []

# we need an array to store the new solution wothout over-writing the previous solution
# until we have finished iterating over i
x_new = np.zeros_like(b)

def jacobi(A, b, x):
# Iterate up to  user-specified max number of iterations, we will 'break'
# this loop if we hit our convergence tolerance
    for k in range(it_max):
        for i in range(A.shape[0]):
            x_new[i] = (1./A[i, i]) * ( b[i] - ( A[i, :i] @ x[:i] ) - ( A[i, i+1:] @ x[i+1:] ) ) 
    # calculate the norm of the residual r = Ax-b for this latest guess
        residual = np.linalg.norm( ( A @ x_new ) - b )
    # store it for later plotting
        residuals.append(residual)  
        delta_x.append( np.linalg.norm( x_new - x ) )  
    # if less than our required tolerance jump out of the iteration and end.
        if (residual < tol):
            break
    # update the solution at the previous iteration with our solution from finishing this iteration
        x = np.copy(x_new) 

    
jacobi(A, b, x)
    
print('Solution from our Jacobi implementation: \n', x_new)  # our solution vector
print('\nSolution from Scipy, sl.solve(A,b): \n', sl.solve(A,b))  # check against scipy

Solution from our Jacobi implementation: 
 [-0.1634080711828076 -0.0153270060958512  0.2733525902400887
  0.3689354768786032]

Solution from Scipy, sl.solve(A,b): 
 [-0.1634081583393676 -0.0153270576876659  0.2733526430123099
  0.3689355539464156]


In [60]:
A = np.array([[5, -2, 3], 
              [-3, 9, 1],
              [2, -1, -7]])
b = np.array([-1., 2., 3.])
print(b)
# An initial guess at the solution.
x = np.zeros_like(b)
# With no prior knowledge we can't really do anything  
# other than just impose a vector of zeros

 

# A user-defined iteration tolerance
tol = 1.e-6  

 

# A user-specified upper limit on number of iterations to stop at
# if we don't hit tolerance
it_max = 100

 

# Store the residuals for later plotting - we don't know how long this needs to
# be as we don't know how many iterations we will conduct, so initialise an 
# empty list which we will append results to in the loop below
residuals = []
# and also change in solution between iterations
delta_x = []

 

# we need an array to store the new solution without over-writing the previous solution
# until we have finished iterating over i
x_new = np.zeros_like(b)

 

# Iterate up to  user-specified max number of iterations, we will 'break'
# this loop if we hit our convergence tolerance
for k in range(it_max):
    for i in range(A.shape[0]):
        x_new[i] = (1./A[i, i]) * ( b[i] - ( A[i, :i] @ x[:i] ) - ( A[i, i+1:] @ x[i+1:] ) ) 
    # calculate the norm of the residual r = Ax-b for this latest guess
    residual = np.linalg.norm( ( A @ x_new ) - b )
    # store it for later plotting
    residuals.append(residual)  
    delta_x.append( np.linalg.norm( x_new - x ) )  
    # if less than our required tolerance jump out of the iteration and end.
    if (residual < tol):
        break
    # update the solution at the previous iteration with our solution from finishing this iteration
    x = np.copy(x_new) 

 

    
print('Solution from our Jacobi implementation: \n', x_new)  # our solution vector
print('\nSolution from Scipy, sl.solve(A,b): \n', sl.solve(A,b))  # check against scipy

[-1.  2.  3.]
Solution from our Jacobi implementation: 
 [ 0.1861198712210274  0.3312303191401251 -0.4227128971440876]

Solution from Scipy, sl.solve(A,b): 
 [ 0.1861198738170347  0.3312302839116719 -0.4227129337539432]


In [61]:
A = np.array([[10., 2., 3., 5., 3., 5., 7., 9., 11., 2.],
            [1., 14., 6., 2., 8., 12., -4., -1., 10., 7.],
              [-1., 4., 16., -4, 2., 4., 5.,  -5.,  12., 2.],
              [5., 4., 3., 20., 3., -1., 4., 2., -9., 10.],
              [1., 2., 3., 16., 37., 41., 12., 3., 6., 12.],
              [-4., -4., 8., 2., -15., 56., 34., 9., 1., 2.],
              [2., 14., 51., 6., -3., -7., 90., -9., -2., -82.],
             [4., 5., 1., 61., 8., 7., -11., 100., 23., -2.],
              [1., 15., 1., 5., -1., 6., 12., 7., 115., -52.],
              [1.,7., 81., -1., -4., -15., 0., 6., 2., 158.]])
b = np.array([-1., 2., 3., 4, 7, 2, 1, 8, 3, 2])

# An initial guess at the solution.
x = np.zeros_like(b)
# With no prior knowledge we can't really do anything  
# other than just impose a vector of zeros

 

# A user-defined iteration tolerance
tol = 1.e-6  

 

# A user-specified upper limit on number of iterations to stop at
# if we don't hit tolerance
it_max = 100

 

# Store the residuals for later plotting - we don't know how long this needs to
# be as we don't know how many iterations we will conduct, so initialise an 
# empty list which we will append results to in the loop below
residuals = []
# and also change in solution between iterations
delta_x = []

 

# we need an array to store the new solution without over-writing the previous solution
# until we have finished iterating over i
x_new = np.zeros_like(b)

 

# Iterate up to  user-specified max number of iterations, we will 'break'
# this loop if we hit our convergence tolerance
for k in range(it_max):
    for i in range(A.shape[0]):
        x_new[i] = (1./A[i, i]) * ( b[i] - ( A[i, :i] @ x[:i] ) - ( A[i, i+1:] @ x[i+1:] ) ) 
    # calculate the norm of the residual r = Ax-b for this latest guess
    residual = np.linalg.norm( ( A @ x_new ) - b )
    # store it for later plotting
    residuals.append(residual)  
    delta_x.append( np.linalg.norm( x_new - x ) )  
    # if less than our required tolerance jump out of the iteration and end.
    if (residual < tol):
        break
    # update the solution at the previous iteration with our solution from finishing this iteration
    x = np.copy(x_new) 

 

    
print('Solution from our Jacobi implementation: \n', x_new)  # our solution vector
print('\nSolution from Scipy, sl.solve(A,b): \n', sl.solve(A,b))  # check against scipy

Solution from our Jacobi implementation: 
 [-0.0449501887072258 -0.2153150885672472  0.3285939056908601
  0.3548214468141619 -0.0097263419608227  0.1576273227964504
 -0.2810855068734955 -0.1736524514817892  0.0124457424014677
 -0.122573426731788 ]

Solution from Scipy, sl.solve(A,b): 
 [-0.0449501983956219 -0.2153150865507259  0.3285939077523064
  0.354821442165951  -0.0097263392115285  0.1576273239264643
 -0.2810855084723864 -0.173652456899457   0.0124457406409502
 -0.1225734273376865]


In [71]:
A = np.array([[10,   1, 2,  3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], 
             [2, 14,   2,  6, 5, 4, 1, 8, 7, 4,  3, 12, 7,   1],
             [3,  2, 23,   2, 4, 5, 9, 1, 3, 5,  1,  2, 7,  5], 
             [1,  2,  1, 42,  5, 6, 7, 2, 1, 7,  2,  7, 9,  4], 
             [3,  7,  5,  2,60,  7, 8, 9, 2, 0,  3,  1, 8,  11], 
             [2,  6,  2,  1, 8, 82,  3, 2, 1, 8,  3, 2, 7,  19],
             [3,  4,  2,  1, 4,  7,120, 1, 5, 2,  2, 1, 5,   5],
             [6,  2,  1,  3, 5,  8,  5,200, 4, 1,  4, 9, 3,   8],
             [3,  1,  2,  4, 2,  9,  7,  8,260,8,  3, 7, 2,   6],
             [1,  4,  8,  3, 10, 11, 3,  6,  4,311, 2,6, 6,   1], 
             [3,  7,  3,  6, 12,  5, 2,  12, 3,  4,402, 4, 5, 2],
             [8,  2,  1,  9, 3,   3, 5,   2, 4,  8,  6, 496, 4, 1], 
             [3,  7,  1,  5, 7,   8, 4,   1, 5,  7,  3,   1,530, 8],
             [1, 5,   2,  6, 2,   5, 1,   4, 8,  9,  1,   6, 13, 606]])

 

b = np.array([-1., 2., 3., 4, 7, 2, 1, 8, 3, 2, 6, 2, 1, 5])


# An initial guess at the solution.
x = np.zeros_like(b)
# With no prior knowledge we can't really do anything  
# other than just impose a vector of zeros

 

# A user-defined iteration tolerance
tol = 1.e-6  

 

# A user-specified upper limit on number of iterations to stop at
# if we don't hit tolerance
it_max = 100

 

# Store the residuals for later plotting - we don't know how long this needs to
# be as we don't know how many iterations we will conduct, so initialise an 
# empty list which we will append results to in the loop below
residuals = []
# and also change in solution between iterations
delta_x = []

 

# we need an array to store the new solution without over-writing the previous solution
# until we have finished iterating over i
x_new = np.zeros_like(b)

 

# Iterate up to  user-specified max number of iterations, we will 'break'
# this loop if we hit our convergence tolerance
for k in range(it_max):
    for i in range(A.shape[0]):
        x_new[i] = (1./A[i, i]) * ( b[i] - ( A[i, :i] @ x[:i] ) - ( A[i, i+1:] @ x[i+1:] ) ) 
    # calculate the norm of the residual r = Ax-b for this latest guess
    residual = np.linalg.norm( ( A @ x_new ) - b )
    # store it for later plotting
    residuals.append(residual)  
    delta_x.append( np.linalg.norm( x_new - x ) )  
    # if less than our required tolerance jump out of the iteration and end.
    if (residual < tol):
        break
    # update the solution at the previous iteration with our solution from finishing this iteration
    x = np.copy(x_new) 

 

    
print('Solution from our Jacobi implementation: \n', x_new)  # our solution vector
print('\nSolution from Scipy, sl.solve(A,b): \n', sl.solve(A,b))  # check against scipy

Solution from our Jacobi implementation: 
 [-2.5981031037549923e-01  5.4911135579093072e-02  1.2647779181822200e-01
  7.7884700590545003e-02  1.0005357782570833e-01  9.9170806775098277e-03
  5.1790607641406354e-03  4.1572858292682299e-02  9.2977665314876341e-03
 -2.1630688089941791e-03  9.2955765580821047e-03  5.2842725477643768e-03
 -1.4503783479623552e-04  6.1877843756420617e-03]

Solution from Scipy, sl.solve(A,b): 
 [-2.5981030071050326e-01  5.4911142884911571e-02  1.2647779642316095e-01
  7.7884702743451828e-02  1.0005358071814249e-01  9.9170823978551766e-03
  5.1790617944305296e-03  4.1572859068676866e-02  9.2977669967857710e-03
 -2.1630682409821559e-03  9.2955770693367110e-03  5.2842729098754619e-03
 -1.4503750326505009e-04  6.1877845820010290e-03]


In [76]:
A = np.array([[10., 2., 3., 5., 6., 7.],
              [1., 14., 6., 2., 8., 12.],
              [-1., 4., 23., -4, 2., 3.],
              [5., 4., 3., 37., 4., 22],
              [23., 3., 2., 4., 75., 1.],
              [ 12., 1., 2., 4., 33., 94]]) 

b = np.array([6., 3., 7., 3, 9, 2])


# An initial guess at the solution.
x = np.zeros_like(b)
# With no prior knowledge we can't really do anything  
# other than just impose a vector of zeros

 

# A user-defined iteration tolerance
tol = 1.e-6  

 

# A user-specified upper limit on number of iterations to stop at
# if we don't hit tolerance
it_max = 100

 

# Store the residuals for later plotting - we don't know how long this needs to
# be as we don't know how many iterations we will conduct, so initialise an 
# empty list which we will append results to in the loop below
residuals = []
# and also change in solution between iterations
delta_x = []

 

# we need an array to store the new solution without over-writing the previous solution
# until we have finished iterating over i
x_new = np.zeros_like(b)

 

# Iterate up to  user-specified max number of iterations, we will 'break'
# this loop if we hit our convergence tolerance
for k in range(it_max):
    for i in range(A.shape[0]):
        x_new[i] = (1./A[i, i]) * ( b[i] - ( A[i, :i] @ x[:i] ) - ( A[i, i+1:] @ x[i+1:] ) ) 
    # calculate the norm of the residual r = Ax-b for this latest guess
    residual = np.linalg.norm( ( A @ x_new ) - b )
    # store it for later plotting
    residuals.append(residual)  
    delta_x.append( np.linalg.norm( x_new - x ) )  
    # if less than our required tolerance jump out of the iteration and end.
    if (residual < tol):
        break
    # update the solution at the previous iteration with our solution from finishing this iteration
    x = np.copy(x_new) 

    
print('Solution from our Jacobi implementation: \n', x_new)  # our solution vector
print('\nSolution from Scipy, sl.solve(A,b): \n', sl.solve(A,b))  # check against scipy

Solution from our Jacobi implementation: 
 [ 0.5448579047981725  0.1027892944576394  0.3195280868893182
 -0.0021888307338386 -0.0591499214228572 -0.0353258637989162]

Solution from Scipy, sl.solve(A,b): 
 [ 0.5448779297284441  0.1028046448257897  0.3195298344093171
 -0.0021785888771872 -0.0591417654624513 -0.0353192218576182]
